//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.Partner_products = new HashSet<Partner_products>();
        }
    
        public int Id { get; set; }
        public int Тип_партнёра { get; set; }
        public string Наименование_партнёра { get; set; }
        public string Директор { get; set; }
        public string Электронная_почта_партнёра { get; set; }
        public string Телефон_партнёра { get; set; }
        public string Юридический_адрес_партнера { get; set; }
        public string ИНН { get; set; }
        public int Ренйтинг { get; set; }
        public string Скидка { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_products> Partner_products { get; set; }
        public virtual Partners_type Partners_type { get; set; }
    }
}
